apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: enterprise-system-20260527-014614-m8z5kyz7t7sm-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: enterprise-system-20260527-014614-m8z5kyz7t7sm.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: enterprise-system-20260527-014614-m8z5kyz7t7sm-service
            port:
              number: 80
