apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260527-014614-m8z5kyz7t7sm-service
spec:
  selector:
    app: enterprise-system-20260527-014614-m8z5kyz7t7sm
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
